language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install: "pip install -r demo_project/requirements.txt --use-mirrors"
# command to run tests
script: python demo_project/manage.py test graphos demo
services:
  - mongodb
